services:
  airflow_metadata_db:
    image: postgres:15.6
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$POSTGRES_USER"]
      interval: 5s
      retries: 5
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB

  init-airflow:
    build:
      context: ./custom_airflow
      dockerfile: Dockerfile
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=$AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
    depends_on:
      - airflow_metadata_db
    volumes:
      - ./scripts:/opt/airflow/scripts
    command: >
      bash -c "airflow db init && 
               airflow users create --username $AIRFLOW_USER --password $AIRFLOW_PASSWORD --firstname Admin --lastname User --role Admin --email admin@example.com &&
               /opt/airflow/scripts/init_connections.sh"

  redis:
    image: redis:6.2
    ports:
      - 6379:6379
    environment:
        - ALLOW_EMPTY_PASSWORD=yes
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 3

  flower:
    build:
      context: ./custom_airflow
      dockerfile: Dockerfile
    user: $AIRFLOW_UID:$AIRFLOW_GID
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=$AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
      - AIRFLOW__CORE__FERNET_KEY=$AIRFLOW__CORE__FERNET_KEY
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=db+postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@airflow_metadata_db/$POSTGRES_DB
    ports:
      - 5555:5555
    depends_on:
      - redis
    command: ["airflow", "celery", "flower", "--broker=redis://redis:6379/0", "--port=5555"]

  webserver:
    build:
      context: ./custom_airflow
      dockerfile: Dockerfile
    user: $AIRFLOW_UID:$AIRFLOW_GID
    depends_on:
      - airflow_metadata_db
      - scheduler
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/home/airflow/.aws/config
      - ./credentials:/home/airflow/.aws/credentials
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=$AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
      - AIRFLOW__CORE__FERNET_KEY=$AIRFLOW__CORE__FERNET_KEY
      - AIRFLOW__WEBSERVER__DEFAULT_USER_USERNAME=$AIRFLOW_USER
      - AIRFLOW__WEBSERVER__DEFAULT_USER_PASSWORD=$AIRFLOW_PASSWORD
      - TZ=Asia/Taipei
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 30s
      retries: 5
    command: webserver
      
  scheduler:
    build:
      context: ./custom_airflow
      dockerfile: Dockerfile
    user: $AIRFLOW_UID:$AIRFLOW_GID
    depends_on:
      - airflow_metadata_db
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/home/airflow/.aws/config
      - ./credentials:/home/airflow/.aws/credentials
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=$AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
      - AIRFLOW__CORE__FERNET_KEY=$AIRFLOW__CORE__FERNET_KEY
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=db+postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@airflow_metadata_db/$POSTGRES_DB
      - AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL=60
      - TZ=Asia/Taipei
    restart: on-failure
    command: scheduler

  worker:
    build:
      context: ./custom_airflow
      dockerfile: Dockerfile
    user: $AIRFLOW_UID:$AIRFLOW_GID
    depends_on:
      - airflow_metadata_db
      - redis
      - scheduler
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - /var/run/docker.sock:/var/run/docker.sock
      - ./addons/chromedriver:/app/chromedriver
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=$AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
      - AIRFLOW__CORE__FERNET_KEY=$AIRFLOW__CORE__FERNET_KEY
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__CELERY__WORKER_CONCURRENCY=2
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=db+postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@airflow_metadata_db/$POSTGRES_DB
      - TZ=Asia/Taipei
    restart: always
    command: ["airflow", "celery", "worker", "--concurrency=2"]

  selenium:
    image: selenium/standalone-chromium:latest
    container_name: selenium
    ports:
      - "4444:4444"
  
  flights_db:
    image: postgres:15.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=$POSTGRES_FLIGHT_USER
      - POSTGRES_PASSWORD=$POSTGRES_FLIGHT_PASSWORD
      - POSTGRES_DB=$POSTGRES_FLIGHT_DB
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  streamlit:
    build:
      context: ./streamlit
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - POSTGRES_CONN_ID=$POSTGRES_CONN_ID
      - POSTGRES_USER=$POSTGRES_FLIGHT_USER
      - POSTGRES_PASSWORD=$POSTGRES_FLIGHT_PASSWORD
      - POSTGRES_DB=$POSTGRES_FLIGHT_DB
      - POSTGRES_PORT=$POSTGRES_FLIGHT_PORT
    depends_on:
      - webserver